version: "3.9"

services:
  api:
    build: .
    container_name: ecommerce-api
    env_file: .env             
    ports:
      - "${API_PORT-3000}:3000"  
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: ecommerce-db
    env_file: .env             
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT-5432}:5432"   
    restart: unless-stopped

volumes:
  postgres-data:
